# Generated by Django 5.2.3 on 2025-06-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='cretaed_at',
            new_name='created_at',
        ),
    ]
